// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVrgA8IrmKNFTx4HIppI2ufX2LrXYd9sY',
    appId: '1:667379681746:web:508f8ccc1c34af7057a00b',
    messagingSenderId: '667379681746',
    projectId: 'cookup-afee1',
    authDomain: 'cookup-afee1.firebaseapp.com',
    databaseURL: 'https://cookup-afee1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cookup-afee1.appspot.com',
    measurementId: 'G-KQXNXZ6745',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1nfC0n3BQxFMYKAShhz6apvR08KO_E5I',
    appId: '1:667379681746:android:d00c42ba9feb284457a00b',
    messagingSenderId: '667379681746',
    projectId: 'cookup-afee1',
    databaseURL: 'https://cookup-afee1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cookup-afee1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoqnBdescJMwtaVat9u2-ALGhvYF1iFXA',
    appId: '1:667379681746:ios:17dc9694949b66af57a00b',
    messagingSenderId: '667379681746',
    projectId: 'cookup-afee1',
    databaseURL: 'https://cookup-afee1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cookup-afee1.appspot.com',
    iosClientId: '667379681746-49864ph8hpqndichvdp18cfgg3nvchkk.apps.googleusercontent.com',
    iosBundleId: 'com.example.backendFlutterIvo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoqnBdescJMwtaVat9u2-ALGhvYF1iFXA',
    appId: '1:667379681746:ios:613d2d248d08026357a00b',
    messagingSenderId: '667379681746',
    projectId: 'cookup-afee1',
    databaseURL: 'https://cookup-afee1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cookup-afee1.appspot.com',
    iosClientId: '667379681746-h34vrcmfjtuhhh6ncge0eebs4t9nugts.apps.googleusercontent.com',
    iosBundleId: 'com.example.backendFlutterIvo.RunnerTests',
  );
}
